(require 'aider)
(require 'magit)
(setq aider-args '("--model" "gemini/gemini-exp-1206"))
(setenv "GEMINI_API_KEY" "AIzaSyCt2OI50LIOuq63QjU-_wF9LuTqPj877cI")
(global-set-key (kbd "C-c a") 'aider-transient-menu))
(provide 'init-aider)
