(require 'nerd-icons)
(add-to-list 'load-path "lib/nerd-icon/data" user-emacs-directory)
(setq nerd-icons-font-family "FiraCode Nerd Font Mono")
(setq nerd-icons-scale-factor 1.5)
(provide 'init-nerd-icon)
